

package org.usfirst.frc1388.frc2019official.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1388.frc2019official.Robot;
//import org.usfirst.frc1388.frc2019official.UsbLogging;
import org.usfirst.frc1388.frc2019official.subsystems.Elevator;

/**
 *
 */
public class ElevatorInit extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	private final Elevator elevator = Robot.elevator;
	
	private final double k_timeout = 10.0;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public ElevatorInit() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        //this.setInterruptible(false);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	//UsbLogging.printLog(">>> " + this.getClass().getSimpleName() + " started");
    	setTimeout(k_timeout);
    	elevator.setMotor(-1, true);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return elevator.isinitialized() || isTimedOut();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	elevator.setMotor(0, false);
    	//UsbLogging.printLog("<<< " + this.getClass().getSimpleName() + " ended");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	//UsbLogging.printLog("<<< " + this.getClass().getSimpleName() + " interrupted");
    	end();
    }
}